# -*- coding: utf-8 -*-
"""CampeonatosBrasileirosPython.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tPJYYqnl-6o37iziRU8t4AagxlECi3xO

***BIBLIOTECAS USADAS***
"""

!pip install requests # Instala o módulo requests
import requests
import pandas as pd
from bs4 import BeautifulSoup

"""**VARIÁVEIS**"""

ano = 2023
serie = "a"
url = f'https://www.cbf.com.br/futebol-brasileiro/competicoes/campeonato-brasileiro-serie-{serie}/{ano}'

"""**BUSCA NA INTERNET**"""

pagina = requests.get(url)
soup = BeautifulSoup(pagina.content, 'html.parser')
indicador = soup.select('.expand-trigger')
times = list(map(lambda time: time.select(' .hidden-xs')[0].text, indicador))
times